set_property PACKAGE_PIN M22 [get_ports a]
set_property IOSTANDARD LVCMOS33 [get_ports a]
set_property IOSTANDARD LVCMOS33 [get_ports b]
set_property IOSTANDARD LVCMOS33 [get_ports c]
set_property IOSTANDARD LVCMOS33 [get_ports s]
set_property PACKAGE_PIN Y22 [get_ports c]
set_property PACKAGE_PIN AB22 [get_ports s]
set_property PACKAGE_PIN N20 [get_ports b]
